### ISSUE TITLE
Ejercicio listo para revisión.

### ISSUE THREAD

**Issue by JuanMaRuizH** [DevAppWeb/roll-a-dice-JuanMaRuizH#1]
Buenas tardes, el ejercicio puede ser revisado.

Gracias. Un saludo.

**Comment by jivanrod** [comment]
Hola Juan Manuel,

Algún comentario sobre el ejercicio.

- Me gusta el uso de la notación alternativa en la programación de la parte de vista pero encuentro un error sintáctico. Al final del bloque if debería de escribirse:

```php
<?php endif; ?>
```

- Por otro lado a nivel funcional se pide que se muestre en pantalla las veces que sale cada número y no los números que han salido. Pista revisa la función array_coun_values

- Empezar a dar un sabor funcional al código. Por ejemplo, teniendo el número de tiradas en $numTiradas, para generar las tiradas podríamos programarlo como: 

```php
$tiradas = array_map(function ($n) {
    return mt_rand(1, 6);
}, array_fill(0, $numTiradas, 0));
```

**Comment by JuanMaRuizH** [comment]
Buenas Jorge.

Gracias por los comentarios y por las mejoras propuestas. He actualizado el repo con los cambios propuestos.

`<?php endif; ?>` 

No me di cuenta de este error.

Un saludo.

JuanMa

**Comment by jivanrod** [comment]
Está muy bien, solo te quedaría ordenar el resultado final por orden ascendente del número de repeticiones.

**Comment by JuanMaRuizH** [comment]
Gracias, pensaba que se refería al número que había salido en la tirada. Lo corrijo. Muchas gracias :D

**Comment by JuanMaRuizH** [comment]
Ejercicio finalizado
